server:
  port: 8080
  servlet:
    context-path: /

spring:
  # todo ?? ??? ??? ??
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
      # create ?????? ?? ? ?? ??? ?? ? ??? ?? ?? - ?? ??
      # create-drop ?????? ?? ? ??? ?? ? ?????? ?? ??? ??? drop - ?? ??
      # update ??? ??? ?? - ?? ??
      # validate ???? ??? ?? ?? ?? - dev, prod
      # none ???? ?? - dev, prod
    show-sql: true # console print sql
    properties:
      hibernate:
        format_sql: true # console print sql ?? ??
        default_batch_fetch_size: 500 # OneToMany ??? ?? ? ?? ???. where in (1, 2, 3, ..., 500)
    open-in-view: false # ??? ????? ?? ??? ???? ??? ??(???, ?????)
  servlet:
    multipart:
      max-file-size: 10MB # ?? ??? ?? ? ?? ??
      max-request-size: 100MB # ?? ??? ?? ? ?? ?? ?? ?? 100MB ??
logging:
  level:
    org.hibernate.type: trace # ???? ??? ?? ? ? ?? ?? ??
    com.app: debug
feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000
